### ISSUE TITLE
SetRole when dying from tesla

### ISSUE THREAD

**Issue by JasKill** [DGvagabond/SCP-008-X#1]
When, being Scp0492, you die on tesla, scp0492 makes you again.

The problem is here, when you die from Tesla, in ev.Killer.Role = your role
https://github.com/DGvagabond/SCP-008-X/blob/55e293e1672702a773162c9b9f0927ca4ee02c3b/Handlers/Player.cs#L55

**Comment by DGvagabond** [comment]
I've gone ahead and added a new if check at the beginning of the Dying event that'll allow the target to die if they've died to Tesla, decontamination, falling into a pit, or from the pocket dimension. The code is as follows:
` if (DamageTypes.FromIndex(ev.HitInformation.Tool).name == "DECONT" ||
                   DamageTypes.FromIndex(ev.HitInformation.Tool).name == "TESLA" ||
                   DamageTypes.FromIndex(ev.HitInformation.Tool).name == "FALLDOWN" ||
                   ev.Target.ReferenceHub.playerEffectsController.GetEffect<Corroding>().Enabled)
            {
                ev.IsAllowed = true;
                return;
            }`
If this does not fix the issue, feel free to ping me in the Discord. I've updated release v1.1.2 to include this change.

**Comment by JasKill** [comment]
Everything is working fine so far. Could you in the future transfer all broadcast/hints to the config so that they could be translated.
https://github.com/DGvagabond/SCP-008-X/blob/c28a701386ddeebd94e84d59c06c336503dc2112/Handlers/Player.cs#L84

Also add the file you forgot to the github Properties\AssemblyInfo.cs
