### ISSUE TITLE
Not all deaths leading to becoming zombie

### ISSUE THREAD

**Issue by Catiatto** [DGvagabond/SCP-008-X#10]
Hello, I had an idea regarding conditions of turning into SCP-049-2. There could be config, that sets, which death will lead to becoming SCP-049-2 and which will kill player. For example dying to infection, being killed by SCP-049-2 and SCP-049 (and maybe other SCPs) while infected would turn player into zombie. In other instances like commiting suicide or shooting infected person wouldn't lead to becoming SCP-049-2. I think it could be great, because you can still avoid becoming zombie and potentially save your teammates by killing yourself/ asking for mercy kill, if you don't have medkit/SCP-500.

**Comment by DGvagabond** [comment]
I'll start working on this after I get home today

**Comment by Catiatto** [comment]
OK, thanks!
