### ISSUE TITLE
Bug: Infection carries over when dying from a grenade while infected

### ISSUE THREAD

**Issue by ghostzvibes** [DGvagabond/SCP-008-X#12]
**Describe the bug**
If you die from a grenade while infected the infection still carries on until you die from it

**To Reproduce**
1. Get Infected
2. die from a grenade
3. die as a zombie from infection

**Expected behavior**
the zombie's infection doesn't carry over.

**Screenshots**

**Client Build (please complete the following information):**
 - Desktop OS: Windows
 - Version No idea, but windows 10 tho

**EXILED Details (please complete the following information):**
 - Version 3.0.0-alpha.52
 - Plugin Version No idea got sent it by my fellow owners, but I assume 2.3.2

**Additional context**

**Comment by DGvagabond** [comment]
From what I was able to isolate, this bug was the result of several MissingMethodExceptions I have since resolved. However, Feel free to test this in the official v3.0 pre-release I am dropping soon.
