### ISSUE TITLE
Server restarts after shooting a zombie

### ISSUE THREAD

**Issue by FweeGamerHD** [DGvagabond/SCP-008-X#14]
**Describe the bug**
As title says, the server just forcefully restarts after throwing some red errors when you shoot a zombie

**To Reproduce**
1. Spawn in a zombie
2. Shoot it
3.  Observe

**Expected behavior**
The Zombie should just take damage and then die

**Screenshots**
-

**Client Build (please complete the following information):**
 - Desktop OS: [e.g. Windows]
 - Version idfk, the newest

**EXILED Details (please complete the following information):**
 - Version 3.0.5
 - Plugin Version 3.0.0.0

**Additional context**
[LocalAdmin Log 2021-10-14 13.57.17.txt](https://github.com/DGvagabond/SCP-008-X/files/7345926/LocalAdmin.Log.2021-10-14.13.57.17.txt)
-

**Comment by PintTheDragon** [comment]
Hey Dylan, I remember this plugin used to spam deaths. Stackoverflow seems pretty death spammy to me.

**Comment by DGvagabond** [comment]
> Hey Dylan, I remember this plugin used to spam deaths. Stackoverflow seems pretty death spammy to me.

What is a Stackoverflow?
