### ISSUE TITLE
OnHurt and OnDying throws NREs and the plugin simply does not work

### ISSUE THREAD

**Issue by GraczBezNicku** [DGvagabond/SCP-008-X#18]
**Describe the bug**
Plugin throws NRE whenever someone gets hurt (or dies), which makes the target not poisoned, which makes the converting mechanic not work at all.

**To Reproduce**
1. Install Plugin
2. Start the server
3. Hurt someone

**Expected behavior**
Target gets poisoned and converts to 008 after death.

**Screenshots**
No screenshots are required.

**Client Build (please complete the following information):**
 - Desktop OS: (not gonna lie I have no idea, the only thing I know it's Linux)
 - Version: -

**EXILED Details (please complete the following information):**
 - Version 5.2.1
 - Plugin Version 3.1.1.1
**Additional context**
No context required.

**Comment by DGvagabond** [comment]
Resolved with Pull Request #19
