### ISSUE TITLE
Zombies having Cola effect

### ISSUE THREAD

**Issue by Oyplap** [DGvagabond/SCP-008-X#2]
Hello,
When a player has the cola effect and turns into a zombie because of the infection, the player (that is now a zombie) keeps the cola effect.

**Comment by DGvagabond** [comment]
The SCP-207 effect will now be forcibly removed after the player succumbs to the SCP-008 infection.

**Comment by Oyplap** [comment]
Thanks man!

**Comment by Oyplap** [comment]
Should I reinstall version 1.0.2.2 for the changes?

**Comment by DGvagabond** [comment]
No, I update on a fluctuating rotation with my work schedule to avoid over-updating in case multiple issues come up. v1.0.2.3 will be published sometime before 5pm CST. :)

**Comment by Oyplap** [comment]
Thank you for the response!
