### ISSUE TITLE
"Zombies made:" Broadcast

### ISSUE THREAD

**Issue by Oyplap** [DGvagabond/SCP-008-X#4]
Hello,
How can i disable this:
![Schermafbeelding 2020-11-22 151814](https://user-images.githubusercontent.com/45702131/99906198-0dbc4d80-2cd6-11eb-813d-d9ed24aac277.png)

I was not a zombie or 049 during that round.

**Comment by DGvagabond** [comment]
That was intended to be apart of the soon-to-come v2.0 release. I must've mixed up the workspaces or something if that's showing up.

**Comment by Oyplap** [comment]
Ah yes, no problem :)

Thanks for the response

**Comment by DGvagabond** [comment]
No problem, just released v2.0 that has a config option to toggle that. Thank you for your reports! :)
