### ISSUE TITLE
Medkits do not prevent humans from becoming zombies

### ISSUE THREAD

**Issue by PatPeter** [DGvagabond/SCP-008-X#7]
**Describe the bug**
Using one medkit does not heal a human of the zombie poison effect. Sometimes they have to use 2-3 medkits before the code finally kicks in and heals them.

**To Reproduce**
Hit 10 humans and have them all try to use medkits. Some of them won't be able to.

**Expected behavior**
Medkits should automatically cure the poison effect.

**Screenshots**

**Client Build (please complete the following information):**
Most recent version of SCP:SL.

**EXILED Details (please complete the following information):**
 - EXILED 2.1.18
 - SCP-008-X 2.0.0.0 (bug also existed on 1.0,3.0)

**Additional context**

**Comment by DGvagabond** [comment]
With medkits, the plugin uses a config value for calculating the chance of curing the infection that is set by the server host and defaults to 50%. The only 100% hard coded cure is SCP-500. Does this still happen when you raise this config value?

**Comment by PatPeter** [comment]
Ah, I believe myself and my community was confused by this, because in the old version of SCP-008 on EXILED medkits instantly healed the infection. I'm having [problems with my config files](https://github.com/KadeDev/Common-Utils/issues/19) right now so I didn't see the config to change this. I'll put the plugin back on the server and try to get the config to stick (it probably won't).
